#!/usr/bin/env ruby

require "fileutils"
require "json"
require 'optparse'

Options = {
  input: "#{__dir__}/foxcats.json",
  svg: "#{__dir__}/svg",
  png: "#{__dir__}/png",
  thumbnails: true
}

OptionParser.new do |opts|
  opts.banner = "Usage: foxcat-generator [options]"

  opts.on("-s", "--svg SVG", "SVG output folder") do |v|
    Options[:svg] = v
  end

  opts.on("-p", "--png PNG", "PNG output folder") do |v|
    Options[:png] = v
  end

  opts.on("-t", "--[no-]thumbnails", "Generate PNG thumbnails") do |v|
    Options[:thumbnails] = v
  end
end.parse!

FileUtils.mkdir_p(Options[:svg])
FileUtils.mkdir_p(Options[:png])

Header = <<END
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
  xmlns="http://www.w3.org/2000/svg"
  xmlns:svg="http://www.w3.org/2000/svg"
  width="128px"
  height="128px"
  viewBox="0 0 750 750"
  style="shape-rendering: geometricPrecision">
END

Footer = <<END
</svg>
END


ARGV.each do |filename|
  dirname = File.dirname(filename)

  json = JSON.parse(File.read(filename))
  name = json.fetch("name", "foxcat")
  layers = json.fetch("layers")

  output = String.new
  output << Header
  output << "<title>#{name}</title>\n"
  output << "<g id=\"#{name}\" transform=\"translate(0,8.508816)\" fill=\"none\">>\n"
  layers.each do |layer|
    output << File.read("#{dirname}/#{layer}") + "\n"
  end
  output << "</g>\n"
  output << Footer

  svg = "#{Options[:svg]}/#{name}.svg"
  png = "#{Options[:png]}/#{name}.png"

  File.write(svg, output)

  system("svgexport #{svg} #{png}") if Options[:thumbnails]
end
